### PR TITLE
Upgrade to Asterisk 17

### PR DESCRIPTION
**Pull request by pc-m**
Depends-On: https://github.com/wazo-platform/asterisk/pull/44
Depends-On: https://github.com/wazo-platform/wazo-res-amqp/pull/7
Depends-On: https://github.com/wazo-platform/asterisk/pull/45

### CODE REVIEW

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by fblackburn1** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Comment by pc-m** [comment]
recheck

**Pull request merged**
